"""

Revision ID: 7ebf05e5bbac
Revises: 1808283a318e
Create Date: 2025-04-26 14:14:42.555570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebf05e5bbac'
down_revision: Union[str, None] = '1808283a318e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'number_of_people')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('number_of_people', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
