"""

Revision ID: 08c385233974
Revises: 803de520e064
Create Date: 2025-05-10 21:21:07.455139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c385233974'
down_revision: Union[str, None] = '803de520e064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accomplishers_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_accomplishers_first_name'), 'accomplishers_', ['first_name'], unique=False)
    op.create_index(op.f('ix_accomplishers_last_name'), 'accomplishers_', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accomplishers_last_name'), table_name='accomplishers_')
    op.drop_index(op.f('ix_accomplishers_first_name'), table_name='accomplishers_')
    op.drop_table('accomplishers_')
    # ### end Alembic commands ###
