"""

Revision ID: 33785d57f836
Revises: 8c3f02f45b0e
Create Date: 2025-04-26 14:39:31.759220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33785d57f836'
down_revision: Union[str, None] = '8c3f02f45b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('number_of_people', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'number_of_people')
    # ### end Alembic commands ###
