"""

Revision ID: 1808283a318e
Revises: 4c6851631aa3
Create Date: 2025-04-26 14:13:28.910656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1808283a318e'
down_revision: Union[str, None] = '4c6851631aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('booking_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'booking_date')
    # ### end Alembic commands ###
