"""

Revision ID: 5b7d56fa9718
Revises: 08c385233974
Create Date: 2025-05-10 21:23:41.892888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7d56fa9718'
down_revision: Union[str, None] = '08c385233974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accomplishers_', sa.Column('info', sa.String(), nullable=True))
    op.alter_column('accomplishers_', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accomplishers_', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('accomplishers_', 'info')
    # ### end Alembic commands ###
