"""

Revision ID: fd5dfa48be89
Revises: 84e85d97494a
Create Date: 2025-05-18 20:19:03.990569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5dfa48be89'
down_revision: Union[str, None] = '84e85d97494a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accomplishers', 'image_file_name_in_mongo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accomplishers', 'image_file_name_in_mongo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
