"""

Revision ID: bd4c307a8438
Revises: 036f45e208fe
Create Date: 2025-04-26 20:02:45.309951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4c307a8438'
down_revision: Union[str, None] = '036f45e208fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('amount_by_dram', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('tours', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('tours', 'amount_by_dram')
    # ### end Alembic commands ###
