"""

Revision ID: 029590a204b3
Revises: 33785d57f836
Create Date: 2025-04-26 15:37:58.592205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029590a204b3'
down_revision: Union[str, None] = '33785d57f836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tours_user_email_key', 'tours', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tours_user_email_key', 'tours', ['user_email'])
    # ### end Alembic commands ###
